# Generated by Django 3.1 on 2020-09-05 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200905_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='job',
            field=models.CharField(choices=[('teacher', 'Teacher'), ('student', 'Student'), ('developer', 'Developer')], max_length=100),
        ),
    ]
