# Generated by Django 3.1 on 2020-09-05 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200905_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='job',
        ),
    ]
