# Generated by Django 3.1 on 2020-09-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_site_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='thumbnail',
            field=models.CharField(default=None, max_length=150),
        ),
    ]
